// ============================================================================
// FILE INI AUTO-GENERATED oleh scripts/generate-assets.mjs — JANGAN diedit manual.
// Tambah aset: taruh file .glb di public/assets/** lalu jalankan:
//   npm run assets:gen
// ============================================================================
import type { GameAsset } from "./asset-types";

export const GAME_ASSETS: GameAsset[] = [
  { id: "kit-1-masjid-quarter", name: "Masjid Quarter", file: "/assets/buildings/kit-1-masjid-quarter.glb", category: "bangunan", group: "kota", order: 1 },
  { id: "kit-2-bazaar-market", name: "Bazaar Market", file: "/assets/buildings/kit-2-bazaar-market.glb", category: "bangunan", group: "kota", order: 2 },
  { id: "kit-3-city-square", name: "City Square", file: "/assets/buildings/kit-3-city-square.glb", category: "bangunan", group: "kota", order: 3 },
  { id: "kit-4-player-build-kit", name: "Player Build Kit", file: "/assets/buildings/kit-4-player-build-kit.glb", category: "bangunan", group: "kota", order: 4 },
  { id: "kit-5-universitas", name: "Universitas", file: "/assets/buildings/kit-5-universitas.glb", category: "bangunan", group: "kota", order: 5 },
  { id: "kit-6-mall", name: "Mall", file: "/assets/buildings/kit-6-mall.glb", category: "bangunan", group: "kota", order: 6 },
  { id: "kit-7-sekolah-dasar", name: "Sekolah Dasar", file: "/assets/buildings/kit-7-sekolah-dasar.glb", category: "bangunan", group: "kota", order: 7 },
  { id: "kit-8-taman-anak", name: "Taman Anak", file: "/assets/buildings/kit-8-taman-anak.glb", category: "bangunan", group: "kota", order: 8 },
  { id: "kit-9-rumah-sakit", name: "Rumah Sakit", file: "/assets/buildings/kit-9-rumah-sakit.glb", category: "bangunan", group: "kota", order: 9 },
  { id: "kit-16-jalan", name: "Jalan", file: "/assets/buildings/kit-16-jalan.glb", category: "bangunan", group: "kota", order: 16 },
  { id: "kit-20-eksterior-2", name: "Eksterior 2", file: "/assets/buildings/kit-20-eksterior-2.glb", category: "bangunan", group: "kota", order: 20 },
  { id: "kit-30-rumah-1-5", name: "Rumah 1–5", file: "/assets/buildings/kit-30-rumah-1-5.glb", category: "bangunan", group: "rumah", order: 30 },
  { id: "kit-31-rumah-6-10", name: "Rumah 6–10", file: "/assets/buildings/kit-31-rumah-6-10.glb", category: "bangunan", group: "rumah", order: 31 },
  { id: "kit-10-interior-masjid", name: "Interior Masjid", file: "/assets/buildings/kit-10-interior-masjid.glb", category: "bangunan", group: "interior", order: 10 },
  { id: "kit-11-interior-universitas", name: "Interior Universitas", file: "/assets/buildings/kit-11-interior-universitas.glb", category: "bangunan", group: "interior", order: 11 },
  { id: "kit-12-interior-mall", name: "Interior Mall", file: "/assets/buildings/kit-12-interior-mall.glb", category: "bangunan", group: "interior", order: 12 },
  { id: "kit-13-interior-sekolah", name: "Interior Sekolah", file: "/assets/buildings/kit-13-interior-sekolah.glb", category: "bangunan", group: "interior", order: 13 },
  { id: "kit-14-interior-taman", name: "Interior Taman", file: "/assets/buildings/kit-14-interior-taman.glb", category: "bangunan", group: "interior", order: 14 },
  { id: "kit-15-interior-rumah-sakit", name: "Interior Rumah Sakit", file: "/assets/buildings/kit-15-interior-rumah-sakit.glb", category: "bangunan", group: "interior", order: 15 },
  { id: "kit-21-interior-2", name: "Interior 2", file: "/assets/buildings/kit-21-interior-2.glb", category: "bangunan", group: "interior", order: 21 },
  { id: "kit-23-interior-asia", name: "Interior Asia", file: "/assets/buildings/kit-23-interior-asia.glb", category: "bangunan", group: "interior", order: 23 },
  { id: "kit-25-interior-eropa", name: "Interior Eropa", file: "/assets/buildings/kit-25-interior-eropa.glb", category: "bangunan", group: "interior", order: 25 },
  { id: "kit-27-interior-afrika", name: "Interior Afrika", file: "/assets/buildings/kit-27-interior-afrika.glb", category: "bangunan", group: "interior", order: 27 },
  { id: "kit-29-interior-amerika", name: "Interior Amerika", file: "/assets/buildings/kit-29-interior-amerika.glb", category: "bangunan", group: "interior", order: 29 },
  { id: "kit-32-interior-rumah-sederhana", name: "Interior Rumah Sederhana", file: "/assets/buildings/kit-32-interior-rumah-sederhana.glb", category: "bangunan", group: "interior", order: 32 },
  { id: "kit-33-interior-rumah-mewah", name: "Interior Rumah Mewah", file: "/assets/buildings/kit-33-interior-rumah-mewah.glb", category: "bangunan", group: "interior", order: 33 },
  { id: "kit-22-asia-timur", name: "Asia Timur", file: "/assets/buildings/kit-22-asia-timur.glb", category: "bangunan", group: "regional", order: 22 },
  { id: "kit-24-eropa", name: "Eropa", file: "/assets/buildings/kit-24-eropa.glb", category: "bangunan", group: "regional", order: 24 },
  { id: "kit-26-afrika", name: "Afrika", file: "/assets/buildings/kit-26-afrika.glb", category: "bangunan", group: "regional", order: 26 },
  { id: "kit-28-amerika", name: "Amerika", file: "/assets/buildings/kit-28-amerika.glb", category: "bangunan", group: "regional", order: 28 },
  { id: "kit-34-diorama-asia", name: "Diorama Asia", file: "/assets/buildings/kit-34-diorama-asia.glb", category: "bangunan", group: "diorama", order: 34 },
  { id: "kit-35-diorama-eropa", name: "Diorama Eropa", file: "/assets/buildings/kit-35-diorama-eropa.glb", category: "bangunan", group: "diorama", order: 35 },
  { id: "kit-36-diorama-cina", name: "Diorama Cina", file: "/assets/buildings/kit-36-diorama-cina.glb", category: "bangunan", group: "diorama", order: 36 },
  { id: "kit-37-diorama-india", name: "Diorama India", file: "/assets/buildings/kit-37-diorama-india.glb", category: "bangunan", group: "diorama", order: 37 },
  { id: "kit-41-diorama-turki", name: "Diorama Turki", file: "/assets/buildings/kit-41-diorama-turki.glb", category: "bangunan", group: "diorama", order: 41 },
  { id: "kit-42-diorama-belanda", name: "Diorama Belanda", file: "/assets/buildings/kit-42-diorama-belanda.glb", category: "bangunan", group: "diorama", order: 42 },
  { id: "kit-43-diorama-jerman", name: "Diorama Jerman", file: "/assets/buildings/kit-43-diorama-jerman.glb", category: "bangunan", group: "diorama", order: 43 },
  { id: "kit-17-vegetasi", name: "Vegetasi", file: "/assets/buildings/kit-17-vegetasi.glb", category: "bangunan", group: "alam", order: 17 },
  { id: "kit-38-pohon-dunia", name: "Pohon Dunia", file: "/assets/buildings/kit-38-pohon-dunia.glb", category: "bangunan", group: "alam", order: 38 },
  { id: "kit-39-bunga-dunia", name: "Bunga Dunia", file: "/assets/buildings/kit-39-bunga-dunia.glb", category: "bangunan", group: "alam", order: 39 },
  { id: "kit-40-tanaman-dunia-2", name: "Tanaman Dunia 2", file: "/assets/buildings/kit-40-tanaman-dunia-2.glb", category: "bangunan", group: "alam", order: 40 },
  { id: "kit-18-props-eksterior", name: "Props Eksterior", file: "/assets/buildings/kit-18-props-eksterior.glb", category: "bangunan", group: "props", order: 18 },
  { id: "kit-19-props-interior", name: "Props Interior", file: "/assets/buildings/kit-19-props-interior.glb", category: "bangunan", group: "props", order: 19 },
  { id: "kit-51-wisata-turki", name: "Wisata Turki", file: "/assets/buildings/kit-51-wisata-turki.glb", category: "bangunan", group: "wisata", order: 51 },
  { id: "kit-52-wisata-palestina", name: "Wisata Palestina", file: "/assets/buildings/kit-52-wisata-palestina.glb", category: "bangunan", group: "wisata", order: 52 },
  { id: "kit-53-wisata-plus", name: "Wisata Plus", file: "/assets/buildings/kit-53-wisata-plus.glb", category: "bangunan", group: "wisata", order: 53 },
  { id: "kit-44-masjidil-haram", name: "Masjidil Haram", file: "/assets/buildings/kit-44-masjidil-haram.glb", category: "bangunan", group: "haji-umroh", order: 44 },
  { id: "kit-45-interior-haram", name: "Interior Haram", file: "/assets/buildings/kit-45-interior-haram.glb", category: "bangunan", group: "haji-umroh", order: 45 },
  { id: "kit-46-mina-jamarat", name: "Mina Jamarat", file: "/assets/buildings/kit-46-mina-jamarat.glb", category: "bangunan", group: "haji-umroh", order: 46 },
  { id: "kit-47-arafah-muzdalifah", name: "Arafah Muzdalifah", file: "/assets/buildings/kit-47-arafah-muzdalifah.glb", category: "bangunan", group: "haji-umroh", order: 47 },
  { id: "kit-48-masjid-nabawi", name: "Masjid Nabawi", file: "/assets/buildings/kit-48-masjid-nabawi.glb", category: "bangunan", group: "haji-umroh", order: 48 },
  { id: "kit-49-ziarah-makkah", name: "Ziarah Makkah", file: "/assets/buildings/kit-49-ziarah-makkah.glb", category: "bangunan", group: "haji-umroh", order: 49 },
  { id: "kit-50-ziarah-madinah", name: "Ziarah Madinah", file: "/assets/buildings/kit-50-ziarah-madinah.glb", category: "bangunan", group: "haji-umroh", order: 50 },
  { id: "01-bima", name: "Bima", file: "/assets/characters/manusia/01-bima.glb", category: "karakter", group: "manusia", order: 1 },
  { id: "02-kevin", name: "Kevin", file: "/assets/characters/manusia/02-kevin.glb", category: "karakter", group: "manusia", order: 2 },
  { id: "03-yosef", name: "Yosef", file: "/assets/characters/manusia/03-yosef.glb", category: "karakter", group: "manusia", order: 3 },
  { id: "05-laras", name: "Laras", file: "/assets/characters/manusia/05-laras.glb", category: "karakter", group: "manusia", order: 5 },
  { id: "06-mei", name: "Mei", file: "/assets/characters/manusia/06-mei.glb", category: "karakter", group: "manusia", order: 6 },
  { id: "07-siti", name: "Siti", file: "/assets/characters/manusia/07-siti.glb", category: "karakter", group: "manusia", order: 7 },
  { id: "08-helena", name: "Helena", file: "/assets/characters/manusia/08-helena.glb", category: "karakter", group: "manusia", order: 8 },
  { id: "09-omar", name: "Omar", file: "/assets/characters/manusia/09-omar.glb", category: "karakter", group: "manusia", order: 9 },
  { id: "10-dani", name: "Dani", file: "/assets/characters/manusia/10-dani.glb", category: "karakter", group: "manusia", order: 10 },
  { id: "11-edo", name: "Edo", file: "/assets/characters/manusia/11-edo.glb", category: "karakter", group: "manusia", order: 11 },
  { id: "12-lukas", name: "Lukas", file: "/assets/characters/manusia/12-lukas.glb", category: "karakter", group: "manusia", order: 12 },
  { id: "13-tala", name: "Tala", file: "/assets/characters/manusia/13-tala.glb", category: "karakter", group: "manusia", order: 13 },
  { id: "14-anya", name: "Anya", file: "/assets/characters/manusia/14-anya.glb", category: "karakter", group: "manusia", order: 14 },
  { id: "15-ayu", name: "Ayu", file: "/assets/characters/manusia/15-ayu.glb", category: "karakter", group: "manusia", order: 15 },
  { id: "16-nuri", name: "Nuri", file: "/assets/characters/manusia/16-nuri.glb", category: "karakter", group: "manusia", order: 16 },
  { id: "17-alif", name: "Alif", file: "/assets/characters/manusia/17-alif.glb", category: "karakter", group: "manusia", order: 17 },
  { id: "18-marco", name: "Marco", file: "/assets/characters/manusia/18-marco.glb", category: "karakter", group: "manusia", order: 18 },
  { id: "19-kwame", name: "Kwame", file: "/assets/characters/manusia/19-kwame.glb", category: "karakter", group: "manusia", order: 19 },
  { id: "20-yan", name: "Yan", file: "/assets/characters/manusia/20-yan.glb", category: "karakter", group: "manusia", order: 20 },
  { id: "21-wulan", name: "Wulan", file: "/assets/characters/manusia/21-wulan.glb", category: "karakter", group: "manusia", order: 21 },
  { id: "22-sofia", name: "Sofia", file: "/assets/characters/manusia/22-sofia.glb", category: "karakter", group: "manusia", order: 22 },
  { id: "23-intan", name: "Intan", file: "/assets/characters/manusia/23-intan.glb", category: "karakter", group: "manusia", order: 23 },
  { id: "24-priya", name: "Priya", file: "/assets/characters/manusia/24-priya.glb", category: "karakter", group: "manusia", order: 24 },
  { id: "h01-harimau", name: "Harimau", file: "/assets/characters/hewan/h01-harimau.glb", category: "karakter", group: "hewan", order: 1 },
  { id: "h02-singa", name: "Singa", file: "/assets/characters/hewan/h02-singa.glb", category: "karakter", group: "hewan", order: 2 },
  { id: "h03-gajah", name: "Gajah", file: "/assets/characters/hewan/h03-gajah.glb", category: "karakter", group: "hewan", order: 3 },
  { id: "h04-panda", name: "Panda", file: "/assets/characters/hewan/h04-panda.glb", category: "karakter", group: "hewan", order: 4 },
  { id: "h05-unta", name: "Unta", file: "/assets/characters/hewan/h05-unta.glb", category: "karakter", group: "hewan", order: 5 },
  { id: "h06-komodo", name: "Komodo", file: "/assets/characters/hewan/h06-komodo.glb", category: "karakter", group: "hewan", order: 6 },
  { id: "h07-jerapah", name: "Jerapah", file: "/assets/characters/hewan/h07-jerapah.glb", category: "karakter", group: "hewan", order: 7 },
  { id: "h08-zebra", name: "Zebra", file: "/assets/characters/hewan/h08-zebra.glb", category: "karakter", group: "hewan", order: 8 },
  { id: "h09-badak", name: "Badak", file: "/assets/characters/hewan/h09-badak.glb", category: "karakter", group: "hewan", order: 9 },
  { id: "h10-kudanil", name: "Kuda Nil", file: "/assets/characters/hewan/h10-kudanil.glb", category: "karakter", group: "hewan", order: 10 },
  { id: "h11-beruang", name: "Beruang", file: "/assets/characters/hewan/h11-beruang.glb", category: "karakter", group: "hewan", order: 11 },
  { id: "h12-beruangkutub", name: "Beruang Kutub", file: "/assets/characters/hewan/h12-beruangkutub.glb", category: "karakter", group: "hewan", order: 12 },
  { id: "h13-serigala", name: "Serigala", file: "/assets/characters/hewan/h13-serigala.glb", category: "karakter", group: "hewan", order: 13 },
  { id: "h14-rubah", name: "Rubah", file: "/assets/characters/hewan/h14-rubah.glb", category: "karakter", group: "hewan", order: 14 },
  { id: "h15-rusa", name: "Rusa", file: "/assets/characters/hewan/h15-rusa.glb", category: "karakter", group: "hewan", order: 15 },
  { id: "h16-kuda", name: "Kuda", file: "/assets/characters/hewan/h16-kuda.glb", category: "karakter", group: "hewan", order: 16 },
  { id: "h17-llama", name: "Llama", file: "/assets/characters/hewan/h17-llama.glb", category: "karakter", group: "hewan", order: 17 },
  { id: "h18-kanguru", name: "Kanguru", file: "/assets/characters/hewan/h18-kanguru.glb", category: "karakter", group: "hewan", order: 18 },
  { id: "h19-penguin", name: "Penguin", file: "/assets/characters/hewan/h19-penguin.glb", category: "karakter", group: "hewan", order: 19 },
  { id: "h20-elang", name: "Elang", file: "/assets/characters/hewan/h20-elang.glb", category: "karakter", group: "hewan", order: 20 },
  { id: "h21-kucing-oranye", name: "Kucing Oranye", file: "/assets/characters/hewan/h21-kucing-oranye.glb", category: "karakter", group: "hewan", order: 21 },
  { id: "h22-kucing-persia", name: "Kucing Persia", file: "/assets/characters/hewan/h22-kucing-persia.glb", category: "karakter", group: "hewan", order: 22 },
  { id: "h23-kucing-hitam", name: "Kucing Hitam", file: "/assets/characters/hewan/h23-kucing-hitam.glb", category: "karakter", group: "hewan", order: 23 },
  { id: "h24-anjing", name: "Anjing", file: "/assets/characters/hewan/h24-anjing.glb", category: "karakter", group: "hewan", order: 24 },
  { id: "h25-kelinci", name: "Kelinci", file: "/assets/characters/hewan/h25-kelinci.glb", category: "karakter", group: "hewan", order: 25 },
  { id: "h26-hamster", name: "Hamster", file: "/assets/characters/hewan/h26-hamster.glb", category: "karakter", group: "hewan", order: 26 },
  { id: "h27-kurakura", name: "Kura-kura", file: "/assets/characters/hewan/h27-kurakura.glb", category: "karakter", group: "hewan", order: 27 },
  { id: "h28-bebek", name: "Bebek", file: "/assets/characters/hewan/h28-bebek.glb", category: "karakter", group: "hewan", order: 28 },
  { id: "h29-semut", name: "Semut", file: "/assets/characters/hewan/h29-semut.glb", category: "karakter", group: "hewan", order: 29 },
  { id: "h30-pudel", name: "Pudel", file: "/assets/characters/hewan/h30-pudel.glb", category: "karakter", group: "hewan", order: 30 },
  { id: "h31-korgi", name: "Korgi", file: "/assets/characters/hewan/h31-korgi.glb", category: "karakter", group: "hewan", order: 31 },
  { id: "h32-husky", name: "Husky", file: "/assets/characters/hewan/h32-husky.glb", category: "karakter", group: "hewan", order: 32 },
  { id: "h33-kucing-siam", name: "Kucing Siam", file: "/assets/characters/hewan/h33-kucing-siam.glb", category: "karakter", group: "hewan", order: 33 },
  { id: "h34-marmut", name: "Marmut", file: "/assets/characters/hewan/h34-marmut.glb", category: "karakter", group: "hewan", order: 34 },
  { id: "h35-landak", name: "Landak", file: "/assets/characters/hewan/h35-landak.glb", category: "karakter", group: "hewan", order: 35 },
  { id: "h36-kakatua", name: "Kakatua", file: "/assets/characters/hewan/h36-kakatua.glb", category: "karakter", group: "hewan", order: 36 },
  { id: "h37-parkit", name: "Parkit", file: "/assets/characters/hewan/h37-parkit.glb", category: "karakter", group: "hewan", order: 37 },
  { id: "h38-ayam", name: "Ayam", file: "/assets/characters/hewan/h38-ayam.glb", category: "karakter", group: "hewan", order: 38 },
  { id: "h39-ikan-koki", name: "Ikan Koki", file: "/assets/characters/hewan/h39-ikan-koki.glb", category: "karakter", group: "hewan", order: 39 },
];
